// Katalog aller bekannten MCP-Server
// Wird in der Extension als Browse-Quelle genutzt

const SERVER_CATALOG = [
  // --- Daten-Server ---
  {
    name: "solana-mcp-server",
    displayName: "Solana Blockchain",
    description: "Wallet balances, token prices, DeFi yields, safety checks on Solana",
    category: "Crypto & DeFi",
    tools: 11,
    install: { command: "uvx", args: ["solana-mcp-server"] },
    pypi: "https://pypi.org/project/solana-mcp-server/",
    github: "https://github.com/AiAgentKarl/solana-mcp-server",
    requiresApiKey: true,
  },
  {
    name: "openmeteo-mcp-server",
    displayName: "Weather & Climate",
    description: "Global weather, forecasts, air quality, historical data, marine conditions",
    category: "Weather & Environment",
    tools: 6,
    install: { command: "uvx", args: ["openmeteo-mcp-server"] },
    pypi: "https://pypi.org/project/openmeteo-mcp-server/",
    github: "https://github.com/AiAgentKarl/weather-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "agriculture-mcp-server",
    displayName: "Agriculture & Food",
    description: "FAO crop data, soil analysis, food nutrition, agricultural statistics",
    category: "Science & Research",
    tools: 8,
    install: { command: "uvx", args: ["agriculture-mcp-server"] },
    pypi: "https://pypi.org/project/agriculture-mcp-server/",
    github: "https://github.com/AiAgentKarl/agriculture-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "germany-mcp-server",
    displayName: "Germany Open Data",
    description: "German government data — Destatis, Bundesanzeiger, public registers",
    category: "Government & Public Data",
    tools: 10,
    install: { command: "uvx", args: ["germany-mcp-server"] },
    pypi: "https://pypi.org/project/germany-mcp-server/",
    github: "https://github.com/AiAgentKarl/germany-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "space-mcp-server",
    displayName: "Space & NASA",
    description: "NASA APOD, asteroids, Mars rover photos, space weather, ISS tracking",
    category: "Science & Research",
    tools: 8,
    install: { command: "uvx", args: ["space-mcp-server"] },
    pypi: "https://pypi.org/project/space-mcp-server/",
    github: "https://github.com/AiAgentKarl/space-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "aviation-mcp-server",
    displayName: "Aviation & Flights",
    description: "Flight tracking, airport info, airline data, aviation statistics",
    category: "Transport & Travel",
    tools: 7,
    install: { command: "uvx", args: ["aviation-mcp-server"] },
    pypi: "https://pypi.org/project/aviation-mcp-server/",
    github: "https://github.com/AiAgentKarl/aviation-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "eu-company-mcp-server",
    displayName: "EU Company Data",
    description: "European company search, financial filings, beneficial owners, LEI lookup",
    category: "Business & Finance",
    tools: 8,
    install: { command: "uvx", args: ["eu-company-mcp-server"] },
    pypi: "https://pypi.org/project/eu-company-mcp-server/",
    github: "https://github.com/AiAgentKarl/eu-company-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "cybersecurity-mcp-server",
    displayName: "Cybersecurity & CVE",
    description: "CVE vulnerability search, threat intelligence, exploit data",
    category: "Security",
    tools: 7,
    install: { command: "uvx", args: ["cybersecurity-mcp-server"] },
    pypi: "https://pypi.org/project/cybersecurity-mcp-server/",
    github: "https://github.com/AiAgentKarl/cybersecurity-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "medical-data-mcp-server",
    displayName: "Medical & Health",
    description: "WHO data, disease info, drug databases, clinical trials",
    category: "Health & Medical",
    tools: 8,
    install: { command: "uvx", args: ["medical-data-mcp-server"] },
    pypi: "https://pypi.org/project/medical-data-mcp-server/",
    github: "https://github.com/AiAgentKarl/health-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "crossref-academic-mcp-server",
    displayName: "Academic Papers",
    description: "180M+ scientific papers, citations, DOI lookup, author profiles",
    category: "Science & Research",
    tools: 5,
    install: { command: "uvx", args: ["crossref-academic-mcp-server"] },
    pypi: "https://pypi.org/project/crossref-academic-mcp-server/",
    github: "https://github.com/AiAgentKarl/crossref-academic-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "legal-court-mcp-server",
    displayName: "Legal & Court Cases",
    description: "3M+ court decisions, case law search, judge analysis, EU law",
    category: "Legal",
    tools: 6,
    install: { command: "uvx", args: ["legal-court-mcp-server"] },
    pypi: "https://pypi.org/project/legal-court-mcp-server/",
    github: "https://github.com/AiAgentKarl/legal-court-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "llm-benchmark-mcp-server",
    displayName: "LLM Benchmarks",
    description: "Compare LLMs — benchmarks, pricing, recommendations for any task",
    category: "AI & Development",
    tools: 5,
    install: { command: "uvx", args: ["llm-benchmark-mcp-server"] },
    pypi: "https://pypi.org/project/llm-benchmark-mcp-server/",
    github: "https://github.com/AiAgentKarl/llm-benchmark-mcp-server",
    requiresApiKey: false,
  },
  // --- Agent-Infrastruktur ---
  {
    name: "agent-memory-mcp-server",
    displayName: "Agent Memory",
    description: "Persistent memory for AI agents — store, retrieve, search knowledge",
    category: "Agent Infrastructure",
    tools: 5,
    install: { command: "uvx", args: ["agent-memory-mcp-server"] },
    pypi: "https://pypi.org/project/agent-memory-mcp-server/",
    github: "https://github.com/AiAgentKarl/agent-memory-mcp-server",
    requiresApiKey: false,
  },
  {
    name: "agent-context-optimizer-mcp",
    displayName: "Context Optimizer",
    description: "Solve context overload — smart tool pruning, relevance scoring, budget tracking",
    category: "Agent Infrastructure",
    tools: 5,
    install: { command: "uvx", args: ["agent-context-optimizer-mcp"] },
    pypi: "https://pypi.org/project/agent-context-optimizer-mcp/",
    github: "https://github.com/AiAgentKarl/agent-context-optimizer-mcp",
    requiresApiKey: false,
  },
  {
    name: "x402-mcp-server",
    displayName: "x402 Payments",
    description: "Micropayments for AI agents — create invoices, verify payments, track revenue",
    category: "Agent Infrastructure",
    tools: 5,
    install: { command: "uvx", args: ["x402-mcp-server"] },
    pypi: "https://pypi.org/project/x402-mcp-server/",
    github: "https://github.com/AiAgentKarl/x402-mcp-server",
    requiresApiKey: false,
  },
];

// Alle Kategorien extrahieren
const CATEGORIES = [...new Set(SERVER_CATALOG.map(s => s.category))].sort();

module.exports = { SERVER_CATALOG, CATEGORIES };
